"""
Information on various Enet devices gathered from
IbnConfig.xml and manufacturer_language_en.properties

"""

device_info = {
    "DVT_BS1BP": {
        "description": "Motion detector",
        "manufacturer": "Gira / Jung",
        "device_class": None,
    },
    "DVT_DA1M": {
        "description": "Dimming actuator 1-gang mini",
        "manufacturer": "Gira / Jung",
        "device_class": "Actuator",
    },
    "DVT_DA1R": {
        "description": "Dimming actuator 1-gang, for rail mounting",
        "manufacturer": "Gira / Jung",
        "device_class": "Actuator",
    },
    "DVT_DA4R": {
        "description": "Dimming actuator 4-gang, for rail mounting",
        "manufacturer": "Gira / Jung",
        "device_class": "Actuator",
    },
    "DVT_ES1M": {
        "description": "Energy detector 1-gang mini",
        "manufacturer": "Gira / Jung",
        "device_class": None,
    },
    "DVT_ES1Z": {
        "description": "Energy detector in SCHUKO housing",
        "manufacturer": "Gira / Jung",
        "device_class": None,
    },
    "DVT_ES4R": {
        "description": "Energy detector 4-gang, for rail mounting",
        "manufacturer": "Gira / Jung",
        "device_class": None,
    },
    "DVT_HS1T": {
        "description": "Hand-held transmitter 1-gang",
        "manufacturer": "Gira / Jung",
        "device_class": None,
    },
    "DVT_HS2": {
        "description": "Hand-held transmitter 2-gang",
        "manufacturer": "Gira / Jung",
        "device_class": None,
    },
    "DVT_HS4": {
        "description": "Hand-held transmitter 4-gang",
        "manufacturer": "Gira / Jung",
        "device_class": None,
    },
    "DVT_JA1M": {
        "description": "Blinds actuator 1-gang mini",
        "manufacturer": "Gira / Jung",
        "device_class": "Actuator",
    },
    "DVT_JA1R": {
        "description": "Blinds actuator 1-gang, for rail mounting",
        "manufacturer": "Gira / Jung",
        "device_class": "Actuator",
    },
    "DVT_RPZS": {
        "description": "Repeater in SCHUKO housing",
        "manufacturer": "Gira / Jung",
        "device_class": None,
    },
    "DVT_S2A1": {
        "description": "Centre plate",
        "manufacturer": "Gira / Jung",
        "device_class": "Actuator",
    },
    "DVT_SA1M": {
        "description": "Switch/push-button actuator 1-gang mini",
        "manufacturer": "Gira / Jung",
        "device_class": "Actuator",
    },
    "DVT_SA1MP": {
        "description": "Switch/push-button actuator with floating contact, 1-gang mini",
        "manufacturer": "Gira / Jung",
        "device_class": "Actuator",
    },
    "DVT_SA1R": {
        "description": "Switch/push-button actuator 1-gang, for rail mounting",
        "manufacturer": "Gira / Jung",
        "device_class": "Actuator",
    },
    "DVT_SA1Z": {
        "description": "Switch/push-button actuator in SCHUKO housing",
        "manufacturer": "Gira / Jung",
        "device_class": "Actuator",
    },
    "DVT_SA2M": {
        "description": "Switch/push-button actuator 2-gang mini",
        "manufacturer": "Gira / Jung",
        "device_class": "Actuator",
    },
    "DVT_SD1M": {
        "description": "DALI gateway 1-gang mini",
        "manufacturer": "Gira / Jung",
        "device_class": "Actuator",
    },
    "DVT_SF1S": {
        "description": "Brightness detector, solar-powered",
        "manufacturer": "Gira / Jung",
        "device_class": None,
    },
    "DVT_SJA1": {
        "description": "Centre plate for blinds control",
        "manufacturer": "Gira / Jung",
        "device_class": "Actuator",
    },
    "DVT_SJAR": {
        "description": "Switch/push-button actuator 8-gang / blinds actuator 4-gang, for rail mounting",
        "manufacturer": "Gira / Jung",
        "device_class": "Actuator",
    },
    "DVT_SV1M": {
        "description": "Push-button controller 1-10 V 1-gang mini",
        "manufacturer": "Gira / Jung",
        "device_class": "Actuator",
    },
    "DVT_UP1A": {
        "description": "Centre plate",
        "manufacturer": "Gira / Jung",
        "device_class": "Actuator",
    },
    "DVT_UP1AV": {
        "description": "Standard centre plate",
        "manufacturer": "Gira / Jung",
        "device_class": "Actuator",
    },
    "DVT_US2M": {
        "description": "Universal radio transmitter 2-gang mini",
        "manufacturer": "Gira / Jung",
        "device_class": None,
    },
    "DVT_WS1BJ": {
        "description": "Transmitter module 1-gang",
        "manufacturer": "Gira / Jung",
        "device_class": None,
    },
    "DVT_WS1BJF50": {
        "description": "Transmitter module F50 A 1-gang",
        "manufacturer": "Gira / Jung",
        "device_class": None,
    },
    "DVT_WS1BJF50C": {
        "description": "Transmitter module F50 CD 1-gang",
        "manufacturer": "Gira / Jung",
        "device_class": None,
    },
    "DVT_WS1BJF50L": {
        "description": "Transmitter module F50 LS 1-gang",
        "manufacturer": "Gira / Jung",
        "device_class": None,
    },
    "DVT_WS2BJ": {
        "description": "Transmitter module 2-gang",
        "manufacturer": "Gira / Jung",
        "device_class": None,
    },
    "DVT_WS2BJF50": {
        "description": "Transmitter module F50 A 2-gang",
        "manufacturer": "Gira / Jung",
        "device_class": None,
    },
    "DVT_WS2BJF50CL": {
        "description": "Transmitter module F50 CD/LS 2-gang",
        "manufacturer": "Gira / Jung",
        "device_class": None,
    },
    "DVT_WS3BJ": {
        "description": "Transmitter module 3-gang",
        "manufacturer": "Gira / Jung",
        "device_class": None,
    },
    "DVT_WS3BJF50": {
        "description": "Transmitter module F50 A 3-gang",
        "manufacturer": "Gira / Jung",
        "device_class": None,
    },
    "DVT_WS3BJF50CL": {
        "description": "Transmitter module F50 CD/LS 3-gang",
        "manufacturer": "Gira / Jung",
        "device_class": None,
    },
    "DVT_WS4BJ": {
        "description": "Transmitter module 4-gang",
        "manufacturer": "Gira / Jung",
        "device_class": None,
    },
    "DVT_WS4BJF50": {
        "description": "Transmitter module F50 A 4-gang",
        "manufacturer": "Gira / Jung",
        "device_class": None,
    },
    "DVT_WS4BJF50CL": {
        "description": "Transmitter module F50 CD/LS 4-gang",
        "manufacturer": "Gira / Jung",
        "device_class": None,
    },
    "IBOX": {
        "description": "eNet server for rail mounting",
        "manufacturer": "Gira / Jung",
        "device_class": None,
    },
    "DVT_WS1BG": {
        "description": "Wall transmitter, 1-gang with inscription space",
        "manufacturer": "Gira",
        "device_class": None,
    },
    "DVT_WS3BG": {
        "description": "Wall transmitter, 3-gang with inscription space",
        "manufacturer": "Gira",
        "device_class": None,
    },
}

channel_config = {
    'CT_1F01': {'description': 'Switching',
                'control': 'FT_INSA.SOO',
                'info': 'FT_INSA.IOO',
                'type': 'actuator'},
    'CT_1F01_DUMMY': {'description': 'Switching',
                      'control': 'FT_INSA.SOO',
                      'info': 'FT_INSA.IOO',
                      'type': 'actuator'},
    'CT_1F02': {'description': 'Dimming',
                'control': 'FT_INDA.ASC',
                'info': 'FT_INDA.ADV',
                'type': 'actuator'},
    'CT_1F03': {'description': 'Venetian blind',
                'control': 'FT_INBA.SAPBP',
                'info': 'FT_INBA.CAPBP',
                'type': 'actuator'},
    'CT_1F05': {'description': 'Switching',
                'control': 'FT_INSArGO.SOO',
                'info': 'FT_INSArGO.IOO',
                'type': 'actuator'},
    'CT_1F06': {'description': 'Repeater actuator', 'type': 'sensor'},
    'CT_1F08': {'description': 'Switching',
                'control': 'FT_INSAv2.SOO',
                'info': 'FT_INSAv2.IOO',
                'type': 'actuator'},
    'CT_1F09': {'description': 'Switching',
                'control': 'FT_INSAv3.SOO',
                'info': 'FT_INSAv3.IOO',
                'type': 'actuator'},
    'CT_1F0B': {'description': 'Switching',
                'control': 'FT_INLAv2_SA.SOO',
                'info': 'FT_INLAv2_SA.IOO',
                'type': 'actuator'},
    'CT_1F0C': {'description': 'Dimming',
                'control': 'FT_INLAv2_DA.ASC',
                'info': 'FT_INLAv2_DA.ADV',
                'type': 'actuator'},
    'CT_1F0D': {'description': 'Switching',
                'control': 'FT_INLAv2_SAS.SOO',
                'info': 'FT_INLAv2_SAS.IOO',
                'type': 'actuator'},
    'CT_1F0E': {'description': '',
                'control': 'FT_INLNS3.ASC',
                'info': '',
                'type': 'actuator'},
    'CT_1F0E_SA': {'description': '',
                   'control': 'FT_INLNS3_SA.SOO',
                   'info': '',
                   'type': 'actuator'},
    'CT_1F10': {'description': 'Venetian blind',
                'control': 'FT_INBAv3.SAPBP',
                'info': 'FT_INBAv3.CAPBP',
                'type': 'actuator'},
    'CT_1F11': {'description': 'Push-button', 'type': 'sensor'},
    'CT_1F12': {'description': 'Push-button', 'type': 'sensor'},
    'CT_1F13': {'description': 'Scene', 'type': 'sensor'},
    'CT_1F15': {'description': 'Scene All On/Off', 'type': 'sensor'},
    'CT_1F18': {'description': 'Threshold',
                'control': '',
                'info': 'FT_INThScS.CAVTH1',
                'type': 'sensor'},
    'CT_1F19': {'description': 'Energy sensor',
                'control': '',
                'info': 'FT_INES.ABAE',
                'type': 'sensor'},
    'CT_1F1B': {'description': 'Motion sensor',
                'control': '',
                'info': 'FT_INMOVS.BA',
                'type': 'sensor'},
    'CT_1F1E': {'description': 'Push-button', 'type': 'sensor'},
    'CT_1F20': {'description': 'Repeater sensor', 'type': 'sensor'}
}

ignored_channel_types = ("CT_DISABLED", "CT_DEVICE", "CT_1F15")
